name: client_store
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  logging: ^1.0.2
  sentry_flutter: ^5.1.0
  client_app:
    git:
      url: git@github.com:lenra-io/client-app.git
      ref: v1.0.0-beta.5
  client_common:
    git:
      url: git@github.com:lenra-io/client-common.git
      ref: v1.0.0-beta.3
  lenra_ui_runner:
    git:
      url: git@github.com:lenra-io/lenra_ui_runner.git
      ref: v1.0.0-beta.75
  lenra_components:
    git:
      url: git@github.com:lenra-io/lenra_components.git
      ref: v1.0.0-beta.45
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: packages/client_common/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: packages/client_common/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
        - asset: packages/client_common/fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
flutter_icons: # see https://pub.dev/packages/flutter_launcher_icons
  image_path: "assets/images/icon-512.png"
  image_path_ios: "assets/images/icon-1024-white-bg.png"
  remove_alpha_ios: true
  android: true
  ios: true
  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/maskable-icon.png"
