name: client
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  logging: ^1.0.2
  sentry_flutter: ^6.18.1
  go_router: ^6.0.1
  client_common:
    git:
      url: https://github.com/lenra-io/client-common.git
      ref: v1.0.0-beta.44
  lenra_ui_runner:
    git:
      url: https://github.com/lenra-io/lenra_ui_runner.git
      ref: v1.0.0-beta.118
  lenra_components:
    git:
      url: https://github.com/lenra-io/lenra_components.git
      ref: v1.0.0-beta.52
  animations: ^2.0.7
  url_launcher: ^6.1.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: packages/client_common/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: packages/client_common/fonts/Source_Sans_Pro/SourceSansPro-SemiBold.ttf
        - asset: packages/client_common/fonts/Source_Sans_Pro/SourceSansPro-Bold.ttf
flutter_icons:
  # Android
  android: true
  image_path: "assets/images/icon-512.png"
  adaptive_icon_background: "#FFFFFF" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/maskable-icon.png"
  # IOS
  ios: true
  image_path_ios: "assets/images/icon-1024-white-bg.png"
  remove_alpha_ios: true
  # Web
  web:
    generate: true
    image_path: "assets/images/icon-512.png"
    background_color: "#FFFFFF"
    theme_color: "#1E232C"
  # Windows
  windows:
    generate: true
    image_path: "assets/images/icon-512.png"
  # MacOS
  macos:
    generate: true
    image_path: "assets/images/icon-512.png"
