name: Android Build
on:
  push:
    branches:
      - main
      - beta
      - alpha

env:
  flutter_version: "3.7.x"

jobs:
  release:
    name: Android Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Flutter & Dependencies
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Flutter Build APK
        run: flutter build apk --no-tree-shake-icons --dart-define=LENRA_SERVER_URL=https://api.lenra.io
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
