name: Release
on:
  push:
    branches:
      - main
      - rc
      - beta
      - alpha
      - "*.x"

jobs:
  get-version:
    uses: lenra-io/github-actions/.github/workflows/get-version.yml@8-task-publish-to-the-playstore
  get-build-number:
    uses: lenra-io/github-actions/.github/workflows/increment-variable.yml@8-task-publish-to-the-playstore
    with:
      variable-name: BUILD_NUMBER
      dry-run: true
  build:
    needs: [get-version, get-build-number]
    uses: lenra-io/github-actions/.github/workflows/build-flutter.yml@8-task-publish-to-the-playstore
    with:
      version: ${{ needs.get-version.outputs.version }}
      build: ${{ needs.get-build-number.outputs.build-number }}
      flutter-version: 3.7.x
  release:
    needs: build
    uses: lenra-io/github-actions/.github/workflows/release-flutter.yml@8-task-publish-to-the-playstore
    with:
      package-name: io.lenra.client
      flutter-version: 3.7.x
  increment-build-number:
    needs: release
    uses: lenra-io/github-actions/.github/workflows/increment-variable.yml@8-task-publish-to-the-playstore
    with:
      variable-name: BUILD_NUMBER