name: Release
on:
  push:
    branches:
      - main
      - beta
      - alpha
      - "*.x"

env:
  flutter_version: "3.7.x"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.LENRA_UI_RUNNER_SSH }}
            ${{ secrets.LENRA_COMPONENTS_SSH }}
            ${{ secrets.CLIENT_COMMON_SSH }}
            ${{ secrets.CLIENT_APP_SSH }}
      - name: Install Flutter & Dependencies
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ env.flutter_version }}
      - name: Build Flutter Web
        run: |
          flutter build web
          cd ..
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache docker build
        uses: actions/cache@v2
        with:
          path: ~/.docker-cache
          key: ${{ runner.os }}-docker
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
          DOCKER_IMAGE: lenra/client
        run: |
          sudo chown $USER:$USER .github/release.sh
          sudo chmod +x .github/release.sh
          npx --force -p conventional-changelog-conventionalcommits@5 -p @semantic-release/exec -p @semantic-release/git -p semantic-release-export-data -p https://github.com/Tlepel/semantic-release.git#fix-versions-share-head semantic-release
